omniauth/omniauth

- lib/omniauth/strategy.rb
The origin is not being propagated from the session to the environment when mocking a failure, meaning that it doesn't get set on the URL. This fixes that.
> Set origin when mocking a failure

- Gemfile
- Gemfile.rack-1.3.x
- lib/omniauth/auth_hash.rb
- lib/omniauth/form.rb
- lib/omniauth/strategies/developer.rb
- spec/omniauth/strategy_spec.rb
We see so many CI failures against ruby 1.8.7 in the PRs on this repo, and due to which, I suppose, this repo seems somewhat inactive recently.
This problem is actually totally unrelated to changesets in those PRs, but it's because we're bundling Hashie 3.x that doesn't support Ruby 1.8.
After merging this, we would be able to merge other good ones such as #820, #828, #829, etcetc.
see: https://github.com/intridea/hashie/blob/master/CHANGELOG.md#210-462014
> Hashie >= 2.1 doesn't support Ruby 1.8 (CI build fix! 🍣🍣🍣=͟͟͞͞)

- .gitignore
- .travis.yml
- Gemfile.rack-master
- lib/omniauth/auth_hash.rb
- lib/omniauth/builder.rb
- lib/omniauth/form.rb
- lib/omniauth/strategies/developer.rb
- omniauth.gemspec
- spec/helper.rb
- spec/omniauth/strategy_spec.rb
Rails master has just moved to requiring the rack master branch which is working on rack 2.0 - This loosens up omniauths requirement to allow for testing and development. I specifically need it for testing devise with rails master
> Loosen the rack requirement to allow for testing with upcoming rack 2

- lib/omniauth.rb
- spec/omniauth_spec.rb
`#add_mock` was stringifying original auth hash.
> Stop mutating given hash in #add_mock

- lib/omniauth/strategy.rb
- spec/helper.rb
- spec/omniauth/strategy_spec.rb
This PR adds an implementation of `initialize_copy` to `OmniAuth::Strategy` that calls `@options.dup`. Since `@options` is a `Hashie::Mash` instance (:see_no_evil:), calling `dup` does a deep copy.
This addresses the issue that I reported in #823 and https://github.com/PracticallyGreen/omniauth-saml/issues/54.
> Duplicate options when a strategy is duplicated

- lib/omniauth/strategy.rb
- spec/omniauth/strategy_spec.rb
Request phase of omniauth store `request.params` in session which are later assigned in env of callback phase. According do docs we should only store query params but in this case both GET and POST params get stored. POST params can contain `authenticity_token` of application to protect form CSRF issues. We shouldn't leak such tokens from POST params.
@sferik @jamesarosen @md5
> security issue in returning post parameters from session in callback phase

- lib/omniauth/auth_hash.rb
- lib/omniauth/key_store.rb
- lib/omniauth/strategy.rb
- spec/omniauth/auth_hash_spec.rb
- spec/omniauth/key_store_spec.rb
We introduced a new logger for Mash due to the huge number of issues
that we get where people try to set keys on their Mash. This change
silences the info messages that get logged when a Mash has a conflict
with a method name.
I had to do this in a kind of hacky way. Since OmniAuth supports Hashie
versions `>= 1.2, < 4`, I can't just hook into the method that we'll be
adding in 3.5.2. As such, I apply an override for the logging method if
the disable method isn't present.
I'm also only overriding the method in versions that have the logging
capability.
If anyone has a better suggestion on how to handle this, I'm open to
suggestions! I'm also open to changing the `KeyStore` name. I went
with that because `OmniAuth::Mash` wouldn't communicate much if you
aren't familiar with Hashie.
Fixes …
> Silence Hashie::Mash logger on Hashie 3.5.0+

- Gemfile
- omniauth.gemspec
Update `jruby-openssl`, `rest-client`, and `rack` dependency requirements to avoid potential dependency-related security issues.
> Dependency security updates

- lib/omniauth/strategy.rb
Some strategies use minitest, and it has enabled warnings by default. So there are long list  of warnings like this: https://travis-ci.org/mkdynamic/omniauth-facebook/jobs/139413665
> Avoid ruby warnings

- lib/omniauth/strategy.rb
- spec/omniauth/strategy_spec.rb
Add `env['omniauth.headers']` which is a hash with header values on the request phase. Closes #804
> Sets omniauth.headers on the request phase

- lib/omniauth/strategy.rb
Hashie::Mash#method_missing is really slow, and it's called many times. Running `rake perf:ips` from https://github.com/intridea/omniauth/pull/775 indicates a 60% performance boost.
Before:
```
Calculating -------------------------------------
ips       649 i/100ms
-------------------------------------------------
ips     6757.6 (±6.3%) i/s -      33748 in   5.013527s
```
After:
```
Calculating -------------------------------------
ips      1028 i/100ms
-------------------------------------------------
ips    10738.5 (±7.0%) i/s -      53456 in   5.001545s
```
> Improve perf by using Hashie::Mash#[]

- Gemfile
- Rakefile
Isolated rack performance tests for the omniauth middleware call.
```
$ bundle exec rake perf:ips
$ bundle exec rake perf:mem CNT=100
```
You can configure the path requests are going to with `GET_PATH=/whatever`
> Performance benchmarks for middleware call

- lib/omniauth/strategy.rb
I noticed that OmniAuth::Strategy::Options inherits from Hashie::Mash, meaning that it will initialize even if what you pass in is nil. Then, memoizing default_options with the ||= syntax achieves the same result as the return. 
I would greatly appreciate any feedback.
Thanks :)
Rae
> simplifies OmniAuth::Strategy.default_options

- lib/omniauth/strategy.rb
- spec/omniauth/strategy_spec.rb
Hello,
In one of my rails app, I use Omniauth with multiple providers.
For each one, I can disconnect by calling a DELETE on `auth/:provider`
```
GET|POST /auth/:provider(.:format)            identities#passthru
GET|POST /auth/:provider/callback(.:format)   identities#callback 
DELETE   /auth/:provider(.:format)            identities#destroy
```
It works fine except on `test_mode`, where destroy requests are mapped as request phases.
> Pass through test_mode with another request method

- lib/omniauth/test/strategy_test_case.rb
The documentation included MyStrategy.new which would return an instance unless it fails due to lack of args.
> docs: TestCase expects class in strategy method array

- Gemfile
- README.md
- Rakefile
- lib/omniauth.rb
- lib/omniauth/strategies/developer.rb
- lib/omniauth/strategy.rb
- omniauth.gemspec
- spec/omniauth/auth_hash_spec.rb
- spec/omniauth/strategies/developer_spec.rb
- spec/omniauth/strategy_spec.rb
This PR allows for renaming or disabling of the origin param per the issue (#910) that @97jaz submitted. [Backwards Compatible]
**Examples**
Default Flow:
```ruby
```
Renaming Origin Param:
```ruby
provider :twitter, ENV['KEY'], ENV['SECRET'], origin_param: 'return_to'
```
Disabling Origin Param:
```ruby
provider :twitter, ENV['KEY'], ENV['SECRET'], origin_param: false
```
> Allow for renaming/disabling of `origin` param

- lib/omniauth/strategy.rb
- spec/omniauth/strategy_spec.rb
@tmilewski This is a follow-up to #912 to apply the same logic to `mock_request_call`.
> Updates mock request phase to use options.origin correctly

- Gemfile
- omniauth.gemspec
A new version of Hashie is out but omniauth is locked to a maximum version of 3.6.0. This PR bumps the max allowable version to just under 3.7.0.
> Allow for using latest version of hashie

- .travis.yml
- Gemfile
- lib/omniauth.rb
- lib/omniauth/builder.rb
- omniauth.gemspec
- spec/omniauth/builder_spec.rb
https://github.com/intridea/hashie/releases/tag/v4.0.0
We released the 4.0.0 release as a major semver change due to multiple non-destructive hash methods being changed to return Mash subclasses instead of plain ol' Ruby hashes. This shouldn't affect the majority of projects, but versioning changes allow projects to choose whether to upgrade or not. 
The other included changes were the result of some yak-shaving I had to do to get CI passing again since it's been failing for 4 months :( 
closes #976
> Allow Hashie version 4.0.x

- omniauth.gemspec
Seeing https://github.com/omniauth/omniauth/pull/977 which fixed the build here, and [seeing that the current hashie master build is broken](https://travis-ci.org/hashie/hashie/jobs/612858905) on an integration spec with Omniauth. 
The only reason to introduce a version restriction for hashie is if you know that a gem is incompatible with a certain version of hashie. Currently we know that omniauth requires hashie >= 3.4.6. There's no need to restrict against a future hashie 5, similarly as there was no need to restrict against hashie 4, which released a while ago and works great with omniauth.
> Do not restrict maximum version of Hashie.

- spec/helper.rb
This file is just macros for tests that strategies can use. It seems that coverage in this is flakey, and we don't need it.
> simplecov ignore strategy_macros

- .travis.yml
People use OmniAuth with new Rubys and we need tests for them.
> Test against Ruby 2.6.6 and 2.7.1

- Gemfile
given ruby 2.7 support added in #1002
silence deprecation warning for ruby 2.7.1 - see: https://travis-ci.org/github/omniauth/omniauth/jobs/683231570
```
/home/travis/.rvm/gems/ruby-2.7.1/gems/json-2.0.4/lib/json/common.rb:156: warning: Using the last argument as keyword parameters is deprecated
```
updated Nov-19 in json gem: https://github.com/flori/json/pull/389/files#diff-1fb83c48ff17d82315a53e5f26bc4996R156
diff: https://github.com/flori/json/compare/v2.0.3...v2.3.0
> Update: Bump json gem to 2.3 for ruby 2.7 support

- lib/omniauth.rb
- lib/omniauth/authenticity_token_protection.rb
- lib/omniauth/strategy.rb
- omniauth.gemspec
- spec/helper.rb
- spec/omniauth/strategies/developer_spec.rb
- spec/omniauth/strategy_spec.rb
- spec/omniauth_spec.rb
Re:
https://github.com/omniauth/omniauth/issues/960
https://github.com/omniauth/omniauth/pull/809
Shoutout @pat, this work was influenced by https://github.com/omniauth/omniauth/pull/963
This would obviously need to be a major version bump due to breaking changes. 
This is based on the ideas of a few others, with some things I added in myself. 
The changes include:  
- Defaulting to POST only allowed request methods
- Use of a `request_validation_phase` specific to this type of workflow. 
- Default request validation phase that should work for _most_ rack based apps, though Rails is a special case 
Example apps available [here](https://github.com/BobbyMcWho/omniauth_2_examples). 
Rails apps will require a special [verification phase](https://github.com/BobbyMcWho/omniauth_2_examples/blob/m …
> RFC - Make omniauth use post by default

- lib/omniauth.rb
- spec/helper.rb
- spec/omniauth/auth_hash_spec.rb
- spec/omniauth/form_spec.rb
- spec/omniauth/key_store_spec.rb
- spec/omniauth/strategy_spec.rb
- spec/omniauth_spec.rb
This also fixes a bug I found while increasing the test coverage, where passing `false` as the second param of `OmniAuth::Utils.camelize` would throw an error due to there not being a method `#first` defined for `String`. The old method would also fail since it would turn 
`camelize('apple_jacks', false)` to `"aPpleJacks"`, now it will correctly do `"appleJacks"`
> Increase test coverage

- lib/omniauth/failure_endpoint.rb
- lib/omniauth/strategy.rb
- spec/omniauth/failure_endpoint_spec.rb
- spec/omniauth/strategy_spec.rb
Rescues from strategy calls by calling fail!, properly URL encodes message_key for FailureEndpoint handling
> Generic error handling in Strategy

- README.md
This changes the few instances of "I" to "you" to match the rest of the README.
> Change first-person to second-person in README

- lib/omniauth/builder.rb
- spec/omniauth/builder_spec.rb
When giving `Builder#provider` the name of a provider as a symbol, the lookup can find a top-level constant by that name. I'm assuming the intention is that providers named by symbols are expected to be defined under `OmniAuth::Strategies`.
i.e. this raises no exception:
```ruby
module FancyService; end
Rails.application.config.middleware.use OmniAuth::Builder do
provider :fancy_service
end
```
Though you don't get an exception immediately, you will get an exception during a request when the middleware actually executes (assuming that top-level constant is not in fact a well-formed strategy).
I ran across this in a Rails development environment, with constant autoloading.  My app defines both a top-level constant `::FancyService` (unrelated to auth) and a nested constant …
> limit Builder#provider's symbol lookup to constants under OmniAuth::Strategies

- lib/omniauth/strategy.rb
These messages are very specific to omniauth internals, and thus are
only useful when debugging or developing. Having these messages on
`:info` causes them to fill test suite output or other non-production
logs which are at the `:info` level. We should move these messages to
`:debug` so developers can still see them, but they do not pollute
non-development logs.
> Change debugging logging to use debug channel

- lib/omniauth/form.rb
One minor change that keeps all tests green when frozen string literals are in play in MRI 2.4+.
I've done this testing by adding the pragma comment to all Ruby files in lib and spec locally, but have not included those changes in this PR. I'm happy to add them in if you'd like, I just don't want to presume whether that's preferred or not.
> Update for frozen-string-literal friendliness.

- lib/omniauth/strategy.rb
- spec/omniauth/strategy_spec.rb
This PR allows OmniAuth to transparently handle relative url root installations by correctly prefixing the default `Strategy#request_path` and `Strategy#callback_path` with `SCRIPT_NAME` as provided by Rack.
Also, in order to detect the full current path, uses `Rack::Request#path` instead of `#path_info`, as the latter does not include SCRIPT_NAME.
A deeper question remains: What should happen with custom callback and request paths? I can't think of a case where a user with a relative url root installation would _not_ want to prefix its paths, regardless of setting a custom path or not.
However, since some people may have configured custom paths in order to deal with relative root, including this change may be breaking.
I have thus included a specific spec that asserts that custom request …
> Deal with relative url root installations

- lib/omniauth/authenticity_token_protection.rb
- spec/omniauth/strategy_spec.rb
This will be useful for disabling csrf protection in test suites or configuring the csrf key when the next version of rack-protection is released.
ie:
```
OmniAuth.config.request_validation_phase = OmniAuth::AuthenticityTokenProtection.new(allow_if: ->(env) { true })
```
or
```
OmniAuth.config.request_validation_phase = OmniAuth::AuthenticityTokenProtection.new(key: :_csrf_token)
```
> Allow OmniAuthAuthenticityTokenProtection options to be configured

- lib/omniauth/strategy.rb
- spec/omniauth/strategy_spec.rb
Readjusts when the authenticity token verification happens in `#mock_call` to align with the execution of the real call.
The current implementation of `mock_call` was verifying the token for all requests, regardless of whether the current path is on the omniauth request path. The change was introduced recently in https://github.com/omniauth/omniauth/commit/1b784ffa5f128bea1a22d7d26477f73bb6b3cd08. See https://github.com/omniauth/omniauth/issues/1032 for details.
This creates two problems:
1. When test mode is on, the authenticity verification logic is run inappropriately against requests where this may not even be wanted.
2. The behavior varies from actual production behavior, potentially allowing bugs to be introduced by unwary developers.
* Move the request validation logic into …
> Ensure mock call verifies authenticity tokens with same logic as real call

- lib/omniauth/strategy.rb
- spec/omniauth/strategy_spec.rb
As a consequence of the changes that were merged in #689, errors
thrown by strategies that utilize other_phase (or more specifically
call_app!), would be caught by omniauth, causing headaches for folks
looking to have those errors handled by their application. This
should allow for errors that come from the app to pass through, while
passing errors that come from the authentication phases to the fail!
handler.
Resolves #1030
> Better handle errors that come from the actual app.

- lib/omniauth/strategy.rb
- spec/omniauth/strategy_spec.rb
This is a fix for warning logging brought up in https://github.com/omniauth/omniauth/pull/1010#discussion_r604382856
The problem is that currently warning message is logged on *every* GET request, not only for a login path. Such messages can bloat application logs very fast
Also, it contradicts this particular piece of documentation ([source](https://github.com/omniauth/omniauth/wiki/Upgrading-to-2.0#get)):
> Because using GET for login poses concerns (see OWASP Cheatsheet), after upgrading OmniAuth **will log a :warn level log with every GET request to a login path** when your OmniAuth.config.allowed_request_methods include :get.
> Warn only on GET requests for a login path

- .github/workflows/truffle_ruby.yml
Currently CI builds agains TruffleRuby 22.3.1 are failed on the `bundle install` step.
```
...
Fetching webrick 1.7.0
Installing webrick 1.7.0
Fetching yard 0.9.28
Installing yard 0.9.28
--- ERROR REPORT TEMPLATE -------------------------------------------------------
...
NoMethodError: undefined method `full_name' for nil:NilClass
/home/runner/.rubies/truffleruby-22.3.0/lib/mri/bundler/installer/parallel_installer.rb:124:in `block (2 levels) in check_for_unmet_dependencies'
/home/runner/.rubies/truffleruby-22.3.0/lib/mri/bundler/installer/parallel_installer.rb:123:in `each'
/home/runner/.rubies/truffleruby-22.3.0/lib/mri/bundler/installer/parallel_installer.rb:123:in `block in check_for_unmet_dependencies'
/home/runner/.rubies/truffleruby-22.3.0/lib/mri/bundler/installer/parallel_installe …
```
> Fix `bundle install` step on CI for TruffleRuby

- lib/omniauth/form.rb
- lib/omniauth/strategies/developer.rb
- spec/omniauth/form_spec.rb
- spec/omniauth/strategies/developer_spec.rb
This changes the default method of the :developer strategy to GET. It does
this by allowing OmniAuth::Form to accept a `:method` option, which is
optional and defaults to 'post', the current behavior. Because the default
behavior remains unchanged, I don't expect this to introduct any breaking
changes.
This allows the developer strategy to work with the directions provided in
the README. Further, it seems that the default action of most stratigies is
to use GET for their callbacks.
Fixes #1087 Fixes #1061 Fixes #957
>    Use GET with :developer strategy.

- .github/workflows/jruby.yml
- .github/workflows/main.yml
- .github/workflows/truffle_ruby.yml
The 18.04 runners are depriciated https://github.blog/changelog/2022-08-09-github-actions-the-ubuntu-18-04-actions-runner-image-is-being-deprecated-and-will-be-removed-by-12-1-22/
I noticed some of the jobs had OS matrixes, but they weren't wired in, so I updated them to actually use those runner
> ci: use ubuntu-latest runner

- .github/dependabot.yml
- .github/workflows/jruby.yml
- .github/workflows/main.yml
- .github/workflows/truffle_ruby.yml
Noticed some of the CI actions were behind, so adding Dependabot to keep them up-to-date automatically through PRs
> chore: add Dependabot for version updates

- Gemfile
- spec/helper.rb
Probably more can be removed since Ruby 2.x is now EOL, but the current spec at least only marks 2.2+ support so these conditions shouldn't apply anymore anyway
> chore: Remove conditions for old (J)Ruby

- .github/workflows/jruby.yml
- lib/omniauth.rb
This seems kind of hacky, but it seems like the bug in Rack was only fixed in v3, and wasn't backported to v2
> fix: conditional delegate require Rack/JRuby

- .github/workflows/main.yml
CRuby < 2.6 does not support macos-arm64, which is what `macos-latest` runs with.
`macos-latest-large` does still run as x86 if you wanted to use that instead https://github.com/actions/runner-images?tab=readme-ov-file#available-images
Example failed run: https://github.com/omniauth/omniauth/actions/runs/10039676811/job/28362997222
> Exclude (macos, 2.5) from test matrix

- lib/omniauth/strategy.rb
- spec/omniauth/strategy_spec.rb
I'm attempting to write a test for our authentication callback Rails controller, however using `ActionDispatch::IntegrationTest` it is not possible to modify the `session`. This change makes it easy to test.
Fixes #934
Example with Rails:
```ruby
class ExampleController < ApplicationController
def callback
redirect_to(env["omniauth.origin"] || "/")
end
end
class ExampleControllerTest < ActionDispatch::IntegrationTest
test "redirects to origin" do
get "/auth/example/callback", env: {"omniauth.origin" => "/foo"}
assert_redirected_to "/foo"
end
end
```
> Do not override `omniauth.origin` in environment in test mode
